" load plugins from vundle
set nocompatible
filetype off

call plug#begin()
" utilities
Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeOpen'] }
" Plug 'jistr/vim-nerdtree-tabs'
" Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-fugitive' " the ultimate git helper
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-commentary' " comment/uncomment lines with gcc or gc in visual mode
Plug 'airblade/vim-gitgutter'
Plug 'Valloric/YouCompleteMe', { 'do': '/home/eggerk/dotfiles/vim/install_ycm.sh $(pwd)' }
Plug 'lervag/vimtex', { 'for': ['tex'] }
Plug 'tpope/vim-obsession'
Plug 'richq/vim-cmake-completion'
Plug 'vim-scripts/DoxygenToolkit.vim'
Plug 'drmikehenry/vim-headerguard', { 'for': ['cpp', 'c'] }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'Chiel92/vim-autoformat'
Plug 'taketwo/vim-ros'
Plug 'chrisbra/csv.vim', { 'for': ['csv'] }
Plug 'ntpeters/vim-better-whitespace'
Plug 'majutsushi/tagbar'
call plug#end()

" filetype plugin indent on

set t_Co=256
set nocompatible " not compatible with vi
set autoread " detect when a file is changed

" make backspace behave in a sane manner
set backspace=indent,eol,start

set clipboard=unnamedplus

" minimal number of of screen lines (context) above and below the cursor
:set scrolloff=5

" enable line numbers
:set ruler
:set number
:set relativenumber
:set showcmd

" No code folding
set nofoldenable

" fold everything that is more than 1 level indented
set foldmethod=syntax
set foldminlines=10
set foldopen+=jump

" No indentation after namespace.
set cino=N-s

" use ctrl-hjkl to switch split
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" open new splits bottom/right
set splitbelow
set splitright
set equalalways


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => User Interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Searching
set ignorecase " case insensitive searching
set smartcase " case-sensitive if expresson contains a capital letter
set hlsearch
set incsearch " set incremental search, like modern browsers

" switch syntax highlighting on
syntax on

set autoindent " automatically set indent of new line
set smartindent

" set tab == 2 spaces
set tabstop=2
set softtabstop=2
set expandtab
set shiftwidth=2
set smarttab

set laststatus=2 " show the satus line all the time
" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2
set mouse=a


colorscheme desert
set cursorline
hi CursorLine cterm=none ctermbg=237
set guifont=Ubuntu\ Mono\ derivative\ Powerline

set colorcolumn=81  " Line at 80 chars.
highlight ColorColumn ctermbg=magenta
highlight Search ctermfg=white
au BufNewFile,BufRead *.tex setlocal colorcolumn=
au VimEnter * :highlight Todo ctermfg=lightgray ctermbg=darkblue
au FileType python set tabstop=2
au FileType python set shiftwidth=2

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Format
noremap <C-F> V:Autoformat<cr>
imap <C-F> <c-o>V:Autoformat<cr>
let g:formatdef_clangformat='"clang-format -style=file -fallback-style=google"'
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
let g:formatters_python=['yapf']
let g:formatter_yapf_style='google'

" Toggle NERDTree
nmap <silent> <leader>k :NERDTreeToggle<cr>
" expand to the path of the file in the current buffer
nmap <silent> <leader>y :NERDTreeFind<cr>
let g:NERDTreeQuitOnOpen=1 " close NERDTree after a file is opened
let NERDTreeShowHidden=1 " show hidden files in NERDTree

let g:airline_powerline_fonts = 1
" let g:airline_theme='solarized'

" GitGutter
set updatetime=500

let g:ycm_global_ycm_extra_conf = '/home/eggerk/dotfiles/vim/ycm/ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_key_list_select_completion = ['<TAB>', '<Down>']
map <leader>g :YcmCompleter GoTo<cr>
map <leader>x :YcmCompleter GoToDefinition<cr>
map <leader>c :YcmCompleter GoToDeclaration<cr>
map <leader>t :YcmCompleter GetType<cr>
map <leader>i :YcmCompleter GoToInclude<cr>
map <leader>h :YcmCompleter GetDoc<cr>

" fzf
map <c-p> :FZF<cr>
map <c-g> :GFiles<cr>
map <c-b> :Buffers<cr>
map <c-s> :Ag<cr>

" Tagbar
map <leader>o :TagbarToggle<cr>
let g:tagbar_autofocus = 1

" Commentary
autocmd FileType c,cpp,cs,java setlocal commentstring=//\ %s
autocmd FileType cmake setlocal commentstring=#\ %s
autocmd BufRead,BufNewFile *.launch setfiletype roslaunch

" Doxygen
let g:DoxygenToolkit_commentType = "C++"
let g:DoxygenToolkit_briefTag_pre="\\brief "
let g:DoxygenToolkit_paramTag_pre="\\param "
let g:DoxygenToolkit_returnTag="\\returns "
let g:DoxygenToolkit_templateParamTag_pre="\\tparam "
let g:DoxygenToolkit_classTag="\\class"
let g:DoxygenToolkit_compactDoc="yes"

" HeaderGuards
function! g:HeaderguardName()
  let project_name = expand('%:p:gs@.*include/\(.*\)/.*@\1@g')
  let project_name = substitute(project_name, '[^0-9a-zA-Z_]', '_', 'g')
  let project_name = toupper(project_name)
  let file_name = toupper(expand('%:t:gs/[^0-9a-zA-Z_]/_/g'))
  return project_name . "_" . file_name . "_"
endfunction

function! g:HeaderguardLine3()
  return "#endif  // " . g:HeaderguardName() . ""
endfunction

" Vim-ros
let g:ros_build_system="catkin-tools"
