#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s="  " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"
make="$(exiv2 -g Image.Make -Pt "$1")"
model="$(exiv2 -g Image.Model -Pt "$1")"
aperture="$(exiv2 -g FNumber -Pt "$1")"
exposure="$(exiv2 -g Exif.Photo.ExposureTime -Pt "$1")"
iso="$(exiv2 -g Exif.Photo.ISOSpeedRatings -Pt "$1")"
focal_length="$(exiv2 -g Exif.Photo.FocalLength\$ -Pt "$1")"
focal_length_35mm="$(exiv2 -g Exif.Photo.FocalLengthIn35mmFilm -Pt "$1")"
exposure_bias="$(exiv2 -g Exif.Photo.ExposureBiasValue -Pt "$1")"

echo "${filename}${s}${filesize}${s}${geometry}${s}${make} ${model}${s}${focal_length} (${focal_length_35mm})${s}${aperture}${s}${exposure}${s}${exposure_bias}${s}ISO ${iso}"
